spring:
  profiles:
    active: test
  application:
    name: single-bridge
---
spring:
  profiles: dev

service:
  config:
    server: http://192.168.10.29:30012
    group: SingleBridge
    module: Single
    branch: DEV
    secretKey: f8127442b9e14ad897d7f3c37cba1a11
  api.enable: true
  reportImgPath: /Users/cludy/project/lanbright/single-bridge/src/main/resources/report.jpg

logging:
  level:
    org.springframework: debug
---
spring:
  profiles: test

service:
  config:
    server: http://192.168.10.29:30012
    group: SingleBridge
    module: Single
    branch: TEST
    secretKey: f8f661c1fe7c4be0b33405f9f47c4880
  api.enable: true
  reportImgPath: /data/app/single/report.jpg
  appStaticHome: /data/app/single/static
logging:
  level:
    org.springframework: debug

