spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: single-bridge

  r2dbc:
    url: ${LOBO_DATASOURCE_URL}
    username: ${LOBO_DATASOURCE_USERNAME}
    password: ${LOBO_DATASOURCE_PASSWORD}
    pool:
      initial-size: 10
      max-size: 10
      validation-query: SELECT 1
  data:
    mongodb:
      uri: ${MONGODB_URI}

service:
  appVersion:
    encryptKey: SMqlkJMxm62b92xoR2d4fg== # 前端应用版本号加密密码
    encryptIv: VlBFZ6Y9Vlmq1a4hb6IRsg== # 前端应用版本号加密密码
  yx:
    host: https://api.netease.im
    appKey: 5496955336632c1d113fed098d9cd53b
    appSecret: 1832c6417bc8
  auth:
    session:
      - '* /user/position/**' # 定位相关功能
      - '* /user/greet/**' # 打招呼相关功能
  config:
    server: ${CONFIG_SERVER_URL}
    group: ${CONFIG_GROUP:SingleBridge}
    module: ${CONFIG_MODULE:Single}
    branch: ${CONFIG_BRANCH:TEST}
    secretKey: ${CONFIG_SECRET_KEY:f8f661c1fe7c4be0b33405f9f47c4880}
  api.enable: true
  reportImgPath: ${REPORT_IMG_PATH:/data/apps/single/single-bridge/report.jpg}
  appStaticHome: ${APP_STATIC_HOME:/data/apps/single/single-bridge/static}