spring:
  profiles:
    active: test
  application:
    name: single-bridge

service:
  appVersion:
    encryptKey: SMqlkJMxm62b92xoR2d4fg== # 前端应用版本号加密密码
    encryptIv: VlBFZ6Y9Vlmq1a4hb6IRsg== # 前端应用版本号加密密码
---
spring:
  profiles: dev

service:
  config:
    server: http://192.168.10.29:30012
    group: SingleBridge
    module: Single
    branch: DEV
    secretKey: f8127442b9e14ad897d7f3c37cba1a11
  api.enable: true
  reportImgPath: /Users/cludy/project/lanbright/single-bridge/src/main/resources/report.jpg

logging:
  level:
    org.springframework: debug
---
spring:
  profiles: test

service:
  config:
    server: http://192.168.10.29:30012
    group: SingleBridge
    module: Single
    branch: TEST
    secretKey: f8f661c1fe7c4be0b33405f9f47c4880
  api.enable: true
  reportImgPath: /data/app/single/single-bridge/report.jpg
  appStaticHome: /data/app/single/single-bridge/static
logging:
  level:
    org.springframework: debug

---
spring:
  profiles: prod

service:
  config:
    server: http://gw.sc-gaea.com:30012
    group: SingleBridge
    module: Single
    branch: PROD
    secretKey: 4e3b2dc72528435ea420dde8dff70aa7
  api.enable: false
  reportImgPath: /data/app/single-bridge/report.jpg

logging:
  config: logback-spring.xml

