spring:
  redis:
    single:
      database: 0
      host: localhost
      port: 6379
      ssl: false
      timeout: 200 # 单位ms
    lobo:
      cluster:
        nodes: node3:6001,node3:6002,node3:6003,node4:6001,node4:6002,node4:6003
  r2dbc:
    url: r2dbc:pool:mysql://10.13.208.3:3306/lobo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: appuser2
    password: password
    pool:
      validation-query: SELECT 1
  data:
    mongodb:
      uri: mongodb://singler:password@localhost:27017/single_bridge

service:
  appVersion:
    encryptKey: SMqlkJMxm62b92xoR2d4fg== # 前端应用版本号加密密码
    encryptIv: VlBFZ6Y9Vlmq1a4hb6IRsg== # 前端应用版本号加密密码
  yx:
    host: https://api.netease.im
    appKey: 5496955336632c1d113fed098d9cd53b
    appSecret: 1832c6417bc8
  auth:
    session:
      - '* /user/position/**' # 定位相关功能
      - '* /user/greet/**' # 打招呼相关功能
  config:
    server: http://gw.sc-gaea.com:30012
    group: SingleBridge
    module: Single
    branch: PROD
    secretKey: 4e3b2dc72528435ea420dde8dff70aa7
  api.enable: false
  reportImgPath: /data/app/single-bridge/report.jpg

logging:
  config: logback-spring.xml