service:
  config:
    server: http://192.168.10.29:30012
    secretKey: f8127442b9e14ad897d7f3c37cba1a11
    group: SingleBridge
    module: Single
    branch: DEV
  api.enable: true
logging:
  level:
    org.springframework: debug
#lobo.host: "http://mgr.vchat.club:19001"
spring:
  profiles:
    active: debug
